### ISSUE TITLE
The disabled popups are still being displayed by the default select interaction

### ISSUE THREAD

**Issue by corentinmarchand** [andreaordonselli/qgis2opengis#2]
Hello,

The default select interaction still queries layers where popups have been turned off.
qgis2opengis version used : 3.19
Export settings :
![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/7f1939e5-37c8-4246-b72f-718031e42fe7)

Webmap popup :
![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/48082add-6cf0-4068-b388-7606dbd3353e)

However, this issue does not appear with the unified popup
![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/3956d728-ce6b-41f8-b7ef-6b087e3a35a0)

**Comment by andreaordonselli** [comment]
Thank you for your recommendation.  I will include the problem in the list of fixes to be made for the next release.

**Comment by andreaordonselli** [comment]
The issue described in this post has been resolved in the v2.20.0 release
Thanks again for the report
