### ISSUE TITLE
Can't export 2 layers with the same name

### ISSUE THREAD

**Issue by corentinmarchand** [andreaordonselli/qgis2opengis#3]
QGis2OpenGIS version : 3.19

Hello, I wanted to report a bug happening when trying to export layers carrying the same name.
Here is a screenshot of my QGIS project where I have two group layers containing 2 layers with the same name : 

![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/7bb75f1b-67b4-48cf-bf40-d1bc559fad07)

When I try to export that project, only the first 2 layers are being displayed and the symbol of those not being displayed have the wrong color in the legend :

![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/79de63c0-ddbc-4146-8df7-e71cb2e059e7)

When I go into the layers folder, I can only see 2 layers despite the console stating it exported all 4 of them: 

![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/057147bb-276d-4caa-8a9b-52ba9dc41bf7)
![image](https://github.com/andreaordonselli/qgis2opengis/assets/165909642/acb29721-3db2-4bc4-950a-ecd47d972317)

When having unique layer names, the export works fine. I think the plugin is either overwriting the js files or writing 2 layers into the same file.

I haven't tried the 3.20 version yet to see if the issue still exists, but the current qgis2web version seems to handle that situation just fine.
Thanks for having a look into this and for all the work you're doing on both plugins!

**Comment by corentinmarchand** [comment]
Thanks for your reply, the output didn't look like an intended behavior so I will keep your recommendation in mind whenever I encounter that situation. Having unique layer names is an easy fix although it can take a bit of time when many automatized outputs are generated with the same name.

**Comment by andreaordonselli** [comment]
Providing different names to the layers also allows you to better understand the data displayed in the popup. If you have two levels called Low Risk you will not distinguish them in the popup, but only as a color on the map.
