### ISSUE TITLE
Bookmark symbol not displayed

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2opengis#5]
Hello,
so that you can see the bookmark symbol:

index.html file: 
Instead of
`<!-- bookmark`

should be written:
`<!-- bookmark -->`

not so important:
Instead of 
`title: "Zoom Localita'",`

should be written:
`title: "Zoom Localita",`

Best greetings

QGIS: 3.36.2
qgis2opengis: 2.20

**Comment by andreaordonselli** [comment]
Thanks for the tip.
Bookmark is deliberately disabled by default. 
User can activate it exactly as you wrote and as it is written in the guide 
https://www.opengis.it/docs/opengis/opengis-configure-the-map/#8-toc-title

Title can be customized as desired.
Greetings.
