### ISSUE TITLE
Iframe integration

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2opengis#6]
Hello,
for the integration of the map as iframe on my own domain, I use a .htaccess file with the following content:

```
#START HTTP Security Header

#Content Security Policy - CSP-HEADER
# Lade Inhalte nur von Seiten die explizit erlaubt sind
# Beispiel: Alles von der eigenen Domain erlauben, keine Externas:

Header set Content-Security-Policy "frame-ancestors 'self'; base-uri 'self'; default-src 'none'; form-action 'self'; img-src 'self' https://mydomain.de data:; font-src 'self' data:; object-src 'none'; script-src 'self' '; style-src 'self';"

```

What do I have to change so that everything is displayed normally?

Screenshot with explanations
![iframe](https://github.com/andreaordonselli/qgis2opengis/assets/31866672/4a76742f-7927-4010-b28b-21624abed4bd)
1) font to big
2) missing icon
3) missing icon
4) Remove overlay (Here I have removed two icons via css (I'm sure there is a better way)
Also minimap is not shown.

Best regards

qgis2opengis 2.20

**Comment by andreaordonselli** [comment]
Has the project export folder been uploaded to the same site? or on other site?
Are you trying to use the iframe because you want to embed the map into a site page?

**Comment by jukos** [comment]
> Has the project export folder been uploaded to the same site? or on other site?
Same site within a folder www.mysite.de/opengis

>  Are you trying to use the iframe because you want to embed the map into a site page?
Yes

**Comment by jukos** [comment]
Thank you very much. It works. Maybe my mistake was, that I did not write my URL in a relative path. Not sure about that.
