### ISSUE TITLE
Text in popup is not displayed completely

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2opengis#8]
Here is a screenshot:
![popup text](https://github.com/user-attachments/assets/a1758280-981d-4aa4-8bb2-85e0e5f10671)

What could be the reason?

Greetings

QGIS: 3.36.3
qgis2opengis: 2.21

**Comment by andreaordonselli** [comment]
Sorry, that's a popup default that I never noticed. Texts longer than 200 characters are cut.
Thanks for the report, I will fix it in the next release, in the meantime set this at the bottom of the index.html file

	<script>
	popup.set('maxChar', '1000');	
	</script>
